### ISSUE TITLE
[Question] Refresh token logic concern

### ISSUE THREAD

**Issue by minhnimble** [kyuuuyki/NimbleSurvey#18] opened 2022-08-01 08:40 UTC
## Issue

Right now I notice that you trigger the refresh token logic before every request in `prerequisiteProcessesForRequest` where the `TargetType` is not `AuthenticationAPITarget` and then check if the token expires or not via the `createdAt` and `expiresIn` attributes. I am curious about why you choose to implement the refresh token logic like this approach? There can be a case I wonder how would you solve it that when the user alters the device's time to make the token expiry check `isExpired` always passes but the token is actually expired from the server point of view? 🤔 At this point, if the users are still active on the current session, they couldn't trigger any request to load the data.

https://github.com/kyuuuyki/NimbleSurvey/blob/b9279c64fba0d01aa01f4cffcbaa1e6542ca2e33/Modules/NimbleCoreAPI/NimbleCoreAPI/Classes/NimbleCoreAPI.swift#L62-L98

**Comment by kyuuuyki** [comment] 2022-08-01 12:33
You are correct. It's true that this logic is likely to cause the problem.

I think to prevent this not-necessary-pre-checking thing, I will let other services call their request first. And then if there is an error with 401 code from the request, I will auto-try the request again after calling refresh token procedure.

https://github.com/kyuuuyki/NimbleSurvey/blob/975847cdccf8c30b0682bfbfc76c7d87d1da5477/Modules/NimbleCoreAPI/NimbleCoreAPI/Classes/NimbleCoreAPI.swift#L63-L85

This should resolve the problems like unnecessary calls or device time altering. There are some concerns like if 401 is not caused by an expired access token but it should be fixed along with access token revoked issue.

**Closed** 2022-08-02 04:06 UTC
